version: "3.8"

services:
  tvproxy:
    build: .
    image: tvproxy:latest
    container_name: tvproxy
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - TVPROXY_BASE_URL=http://localhost
    volumes:
      - tvproxy-config:/config
      - tvproxy-recordings:/record
    # devices:
    #   - /dev/dri:/dev/dri

volumes:
  tvproxy-config:
    external: true
  tvproxy-recordings:
